var Blocklynaite = Blocklynaite || {};
Blocklynaite.LOCALISED_TEXT = {
  translationLanguage: "Fran�ais",
  title: "Blocklynaite",
  blocks: "Blocs",
  /* Menu */
  open: "Ouvrir",
  save: "Enregistrer",
  deleteAll: "Abandonner Tous",
  settings: "",
  documentation: "Documentation",
  reportBug: "",
  examples: "Examples",
  /* Settings */
  compilerLocation: "",
  compilerLocationDefault: "",
  sketchFolder: "",
  sketchFolderDefault: "",
  ESP32Board: "Carte ESP 32",
  ESP32BoardDefault: "Carte ESP 32 inconnu",
  comPort: "",
  comPortDefault: "",
  defaultIdeButton: "",
  defaultIdeButtonDefault: "",
  language: "Langue",
  languageDefault: "Langue inconnu",
  sketchName: "Nom de Sketch",
  /* ESP 32 console output */
  ESP32OpMainTitle: "",
  ESP32OpWaiting: "",
  ESP32OpUploadedTitle: "",
  ESP32OpVerifiedTitle: "",
  ESP32OpOpenedTitle: "",
  ESP32OpOpenedBody: "",
  ESP32OpErrorUpVerTitle: "",
  ESP32OpErrorSketchTitle: "",
  ESP32OpErrorFlagTitle: "",
  ESP32OpErrorFlagPrefTitle: "",
  ESP32OpErrorIdeDirTitle: "",
  ESP32OpErrorIdeDirBody: "",
  ESP32OpErrorIdeOptionTitle: "",
  ESP32OpErrorIdeOptionBody: "",
  ESP32OpErrorIdePortTitle: "",
  ESP32OpErrorIdePortBody: "",
  ESP32OpErrorIdeBoardTitle: "",
  ESP32OpErrorIdeBoardBody: "",
  /* Modals */
  noServerTitle: "",
  noServerTitleBody: "",
  noServerNoLangBody: "",
  addBlocksTitle: "",
  /* Alerts */
  loadNewBlocksTitle: "",
  loadNewBlocksBody: "",
  discardBlocksTitle: "",
  discardBlocksBody: "",
  invalidXmlTitle: "",
  invalidXmlBody: "",
  /* Tooltips */
  uploadingSketch: "",
  uploadSketch: "",
  verifyingSketch: "",
  verifySketch: "",
  openingSketch: "",
  openSketch: "",
  notImplemented: "",
  /* Prompts */
  ok: "OK",
  okay: "Okay",
  cancel: "Annuler",
  return: "Retour",
  /* Cards */
  ESP32SourceCode: "",
  blocksXml: "Blocs XML",
  /* Toolbox Categories*/
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  catInputOutput: "Entree/Sortie",
  catTime: "Temps",
  catAudio: "Audio",
  catMotors: "Moteurs",
  catComms: "Comms",
};
