var Blocklynaite = Blocklynaite || {};
Blocklynaite.LOCALISED_TEXT = {
  translationLanguage: "Nederlands",
  title: "Blocklynaite",
  blocks: "Blocks",
  /* Menu */
  open: "Open",
  save: "Save",
  deleteAll: "Verwijder Alles",
  settings: "",
  documentation: "Documentatie",
  reportBug: "",
  examples: "Voorbeelden",
  /* Settings */
  compilerLocation: "",
  compilerLocationDefault: "",
  sketchFolder: "",
  sketchFolderDefault: "",
  ESP32Board: "",
  ESP32BoardDefault: "",
  comPort: "",
  comPortDefault: "",
  defaultIdeButton: "",
  defaultIdeButtonDefault: "",
  language: "Taal",
  languageDefault: "Language onbekend",
  sketchName:  "",
  /* ESP 32 console output */
  ESP32OpMainTitle:  "",
  ESP32OpWaiting:  "",
  ESP32OpUploadedTitle:  "",
  ESP32OpVerifiedTitle:  "",
  ESP32OpOpenedTitle:  "",
  ESP32OpOpenedBody:  "",
  ESP32OpErrorUpVerTitle:  "",
  ESP32OpErrorSketchTitle:  "",
  ESP32OpErrorFlagTitle:  "",
  ESP32OpErrorFlagPrefTitle:  "",
  ESP32OpErrorIdeDirTitle:  "",
  ESP32OpErrorIdeDirBody:  "",
  ESP32OpErrorIdeOptionTitle:  "",
  ESP32OpErrorIdeOptionBody:  "",
  ESP32OpErrorIdePortTitle:  "",
  ESP32OpErrorIdePortBody:  "",
  ESP32OpErrorIdeBoardTitle:  "",
  ESP32OpErrorIdeBoardBody:  "",
  /* Modals */
  noServerTitle: "",
  noServerTitleBody:  "",
  addBlocksTitle: "",
  /* Alerts */
  loadNewBlocksTitle: "",
  loadNewBlocksBody: "",
  discardBlocksTitle: "",
  discardBlocksBody: "",
  invalidXmlTitle: "",
  invalidXmlBody: "",
  /* Tooltips */
  uploadingSketch: "",
  uploadSketch: "",
  verifyingSketch: "",
  verifySketch: "",
  openingSketch: "",
  openSketch: "",
  notImplemented: "",
  /* Prompts */
  ok: "OK",
  okay: "Okay",
  cancel: "Annuleer",
  return: "Terugkeer",
  /* Cards */
  ESP32SourceCode: "",
  blocksXml: "Blocks XML",
  /* Toolbox Categories*/
  catLogic: "Logica",
  catLoops: "Herhalen",
  catMath: "Wiskunde",
  catText: "Tekst",
  catVariables: "Variabelen",
  catFunctions: "Functies",
  catInputOutput: "In/Output",
  catTime: "Tijd",
  catAudio: "Audio",
  catMotors: "Motoren",
  catComms: "Comms",
};
